# Generated by Django 4.1.3 on 2022-12-01 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_person_delete_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
