# Generated by Django 4.1.3 on 2022-12-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='image.jpg', upload_to=''),
        ),
    ]
